naidusvoe_homepage:
    path:     /
    defaults: { _controller: NaidusvoeBundle:Index:index }
    
naidusvoe_login:
    path: /login
    defaults: { _controller: NaidusvoeBundle:Index:login }

naidusvoe_login_check:
    path: /login_check
    defaults: { _controller: NaidusvoeBundle:Index:loginCheck }

naidusvoe_logout:
    path: /logout

naidusvoe_signup:
    path: /signup
    defaults: { _controller: NaidusvoeBundle:Index:signup }

naidusvoe_signup_action:
    path: /signup/signup_action
    defaults: { _controller: NaidusvoeBundle:Index:signupAct }

naidusvoe_default:
    pattern: /{some}
    defaults: { _controller: NaidusvoeBundle:Index:index }