naidusvoe_homepage:
    path:     /
    defaults: { _controller: NaidusvoeBundle:Index:index }
    
naidusvoe_login:
    path: /login
    defaults: { _controller: NaidusvoeBundle:Index:login }

naidusvoe_login_check:
    path: /login_check
    defaults: { _controller: NaidusvoeBundle:Index:loginCheck }

naidusvoe_logout:
    path: /logout

naidusvoe_signup:
    path: /signup
    defaults: { _controller: NaidusvoeBundle:Index:signup }

naidusvoe_signup_action:
    path: /signup/signup_action
    defaults: { _controller: NaidusvoeBundle:Index:signupAct }

naidusvoe_get_adv_info:
    path: /get/adv_info
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvDetails }

naidusvoe_add_adv:
    path: /add/adv
    defaults: { _controller: NaidusvoeBundle:Advertisment:addNewAdv }

naidusvoe_get_adv:
    pattern: /get/adv/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdv }

naidusvoe_get_trade_advs:
    path: /get/advs/trade/page/{page_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsTrade }

naidusvoe_get_found_advs:
    path: /get/advs/found/page/{page_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsFound }

naidusvoe_get_gift_advs:
    path: /get/advs/gift/page/{page_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsGift }

naidusvoe_get_user_info:
    path: /user/getInfo
    defaults: { _controller: NaidusvoeBundle:User:getInfo }

naidusvoe_get_error_logs_errors:
    path: /dev/error_logs/getErrors
    defaults: { _controller: NaidusvoeBundle:ErrorLog:getErrors }

naidusvoe_error_logs:
    path: /dev/error_logs
    defaults: { _controller: NaidusvoeBundle:ErrorLog:index }

naidusvoe_save_info:
    pattern: /user/{user_id}/saveInfo
    defaults: { _controller: NaidusvoeBundle:User:saveContactInfo }

naidusvoe_change_password:
    pattern: /user/{user_id}/changePassword
    defaults: { _controller: NaidusvoeBundle:User:changePassword }

naidusvoe_change_email:
    pattern: /user/{user_id}/changeEmail
    defaults: { _controller: NaidusvoeBundle:User:changeEmail }

naidusvoe_save_email_notification_settings:
    pattern: /user/{user_id}/saveEmailNotificationSettings
    defaults: { _controller: NaidusvoeBundle:User:saveEmailNotificationSettings }

naidusvoe_save_sms_notification_settings:
    pattern: /user/{user_id}/saveSmsNotificationSettings
    defaults: { _controller: NaidusvoeBundle:User:saveSmsNotificationSettings }

naidusvoe_delete_account:
    path: /user/deleteAccount
    defaults: { _controller: NaidusvoeBundle:User:deleteAccount }

naidusvoe_add_fav:
    path: /user/fav/add/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:addToFav }

naidusvoe_get_user:
    path: /get/user
    defaults: { _controller: NaidusvoeBundle:User:getUser }


#############################################################################
################## Default Routes for AngularJS Routing #####################
#############################################################################
naidusvoe_default_level0:
    pattern: /{some}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level1:
    pattern: /{some}/{some1}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level2:
    pattern: /{some}/{some1}/{some2}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level3:
    pattern: /{some}/{some1}/{some2}/{some3}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level4:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level5:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level6:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}/{some6}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level7:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}/{some6}/{some7}
    defaults: { _controller: NaidusvoeBundle:Index:index }

#############################################################################

naidusvoe_default_level_1:
    pattern: /{some}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_2:
    pattern: /{some}/{some1}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_3:
    pattern: /{some}/{some1}/{some2}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_4:
    pattern: /{some}/{some1}/{some2}/{some3}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_5:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_6:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}/
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level_7:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}/{some6}/
    defaults: { _controller: NaidusvoeBundle:Index:index }


#############################################################################
#############################################################################
#############################################################################