naidusvoe_homepage:
    path:     /
    defaults: { _controller: NaidusvoeBundle:Index:index }
    
naidusvoe_login:
    path: /login
    defaults: { _controller: NaidusvoeBundle:Index:login }

naidusvoe_login_check:
    path: /login_check
    defaults: { _controller: NaidusvoeBundle:Index:loginCheck }

naidusvoe_logout:
    path: /logout

naidusvoe_signup:
    path: /signup
    defaults: { _controller: NaidusvoeBundle:Index:signup }

naidusvoe_signup_action:
    path: /signup/signup_action
    defaults: { _controller: NaidusvoeBundle:Index:signupAct }

naidusvoe_get_adv_info:
    path: /get/adv_info
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvDetails }

naidusvoe_add_adv:
    path: /add/adv
    defaults: { _controller: NaidusvoeBundle:Advertisment:addNewAdv }

naidusvoe_get_adv:
    pattern: /get/adv/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdv }

naidusvoe_get_trade_advs:
    path: /get/advs/trade
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsTrade }

naidusvoe_get_found_advs:
    path: /get/advs/found
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsFound }

naidusvoe_get_gift_advs:
    path: /get/advs/gift
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdvsGift }

####################################################################
############## Default Routes for AngularJS Routing ################
####################################################################
naidusvoe_default_level0:
    pattern: /{some}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level1:
    pattern: /{some}/{some1}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level2:
    pattern: /{some}/{some1}/{some2}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level3:
    pattern: /{some}/{some1}/{some2}/{some3}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level4:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}
    defaults: { _controller: NaidusvoeBundle:Index:index }

naidusvoe_default_level5:
    pattern: /{some}/{some1}/{some2}/{some3}/{some4}/{some5}
    defaults: { _controller: NaidusvoeBundle:Index:index }

####################################################################
####################################################################
####################################################################
