main:
    resource: "@NaidusvoeBundle/Controller/"
    type: annotation

naidusvoe_logout:
    path: /logout

naidusvoe_get_adv:
    pattern: /get/adv/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:getAdv }

naidusvoe_get_user_info:
    path: /user/getInfo
    defaults: { _controller: NaidusvoeBundle:User:getInfo }

naidusvoe_get_user_advs:
    path: /user/getAdvs
    defaults: { _controller: NaidusvoeBundle:User:getUserAdvs }

naidusvoe_delete_user_adv:
    path: /user/deleteUserAdv/{adv_id}
    defaults: { _controller: NaidusvoeBundle:User:deleteUserAdv }

naidusvoe_get_error_logs_errors:
    path: /dev/error_logs/getErrors
    defaults: { _controller: NaidusvoeBundle:ErrorLog:getErrors }

naidusvoe_error_logs:
    path: /dev/error_logs
    defaults: { _controller: NaidusvoeBundle:ErrorLog:index }

naidusvoe_delete_account:
    path: /user/deleteAccount
    defaults: { _controller: NaidusvoeBundle:User:deleteAccount }

naidusvoe_add_fav:
    path: /user/fav/add/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Advertisment:addToFav }

naidusvoe_get_user:
    path: /get/user
    defaults: { _controller: NaidusvoeBundle:User:getUser }

naidusvoe_user_get_favs:
    path: /user/getFavs
    defaults: { _controller: NaidusvoeBundle:User:getFavs }

naidusvoe_delete_fav:
    pattern: /fav/{fav_id}/delete
    defaults: { _controller: NaidusvoeBundle:User:deleteFav }

naidusvoe_save_info:
    pattern: /user/{user_id}/saveInfo
    defaults: { _controller: NaidusvoeBundle:User:saveContactInfo }

naidusvoe_change_password:
    pattern: /user/{user_id}/changePassword
    defaults: { _controller: NaidusvoeBundle:User:changePassword }

naidusvoe_change_email:
    pattern: /user/{user_id}/changeEmail
    defaults: { _controller: NaidusvoeBundle:User:changeEmail }

naidusvoe_save_email_notification_settings:
    pattern: /user/{user_id}/saveEmailNotificationSettings
    defaults: { _controller: NaidusvoeBundle:User:saveEmailNotificationSettings }

naidusvoe_save_sms_notification_settings:
    pattern: /user/{user_id}/saveSmsNotificationSettings
    defaults: { _controller: NaidusvoeBundle:User:saveSmsNotificationSettings }

naidusvoe_send_new_message:
    pattern: /message/send/{user_id}/{adv_id}
    defaults: { _controller: NaidusvoeBundle:Conversation:sendMessage }

naidusvoe_get_user_messages:
    pattern: /conversations/get
    defaults: { _controller: NaidusvoeBundle:Conversation:getConversations }

naidusvoe_get_conversation:
    pattern: /conversation/get/{conv_id}
    defaults: { _controller: NaidusvoeBundle:Conversation:getConversation }