services:
    naidusvoe.user:
        class: NaidusvoeBundle\Services\UserService
        arguments:
            - @security.encoder_factory
            - @security.token_storage
            - @event_dispatcher
            - @doctrine.orm.entity_manager