services:
    naidusvoe.user:
        class: NaidusvoeBundle\Services\UserService
        arguments:
            - @security.encoder_factory
            - @security.token_storage
            - @event_dispatcher
            - @doctrine.orm.entity_manager

    naidusvoe.recaptcha:
        class: NaidusvoeBundle\Services\GoogleRecaptchaService

    naidusvoe.notifier:
        class: NaidusvoeBundle\Services\Notifier
        arguments: [@doctrine.orm.entity_manager, @service_container]

    naidusvoe.advertisement:
        class: NaidusvoeBundle\Services\AdvertisementService
        arguments: [@doctrine.orm.entity_manager]

    naidusvoe.hwi:
        class: NaidusvoeBundle\Services\OAuthUserProvider
        arguments:
            - @session
            - @doctrine.orm.entity_manager
            - @naidusvoe.user