# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'NaidusvoeBundle' ]
    node: null
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs