assetic:
    assets:
        css:
            inputs:
                - 'css/bootstrap.css'
                - 'css/style.css'
                - 'js/vendor/angular-busy/angular-busy.min.css'
                - 'js/vendor/angular-notify/angular-notify.min.css'
        vendors:
            inputs:
                - 'js/vendor/jQuery/jquery-2.1.3.js'
                - 'js/vendor/jQuery/jquery-migrate-1.2.1.js'
                - 'js/vendor/Bootstrap/bootstrap.min.js'
                - 'js/vendor/AngularJS/angular.min.js'
                - 'js/vendor/AngularJS/angular-route.min.js'
                - 'js/vendor/AngularJS/angular-animate.min.js'
                - 'js/vendor/AngularJS/angular-translate.js'
                - 'js/vendor/AngularJS/angular-translate-loader-static-files.js'
                - 'js/vendor/AngularJS/scrollglue.js'
                - 'js/vendor/lightbox/lightbox.js'
                - 'js/vendor/angular-busy/angular-busy.js'
                - 'js/vendor/angular-notify/angular-notify.js'
        modules:
            inputs:
                - 'js/custom/riki34.module.js'
                - 'js/custom/appCore.js'
        services:
            inputs:
                - 'js/custom/Service/riki34.angular.spinner.js'
                - 'js/custom/Service/naidusvoe.settings.service.js'
        models:
            inputs:
                - 'js/custom/Model/advertisement.model.js'
        controllers:
            inputs:
                - 'js/custom/appController.js'
                - 'js/custom/indexController.js'
                - 'js/custom/Controller/tradingController.js'
                - 'js/custom/Controller/giftController.js'
                - 'js/custom/Controller/foundController.js'
                - 'js/custom/Controller/cabinet.controller.js'
                - 'js/custom/Controller/cabinet.advs.controller.js'
                - 'js/custom/Controller/cabinet.messages.controller.js'
                - 'js/custom/Controller/cabinet.settings.controller.js'
                - 'js/custom/Controller/conversation.controller.js'
                - 'js/custom/advertismentController.js'
                - 'js/custom/testController.js'
        directives:
            inputs:
                - 'js/custom/Directive/riki34.paginator.directive.js'
                - 'js/custom/Directive/naidusvoe.adv.directive.js'
                - 'js/custom/Directive/naidusvoe.add.file.directive.js'
