assetic:
    assets:
        css:
            inputs:
                - 'css/bootstrap.css'
                - 'css/style.css'
                - 'css/spinner.css'
                - 'css/font-awesome.min.css'
                - 'js/vendor/angular-busy/angular-busy.min.css'
                - 'js/vendor/angular-notify/angular-notify.min.css'
        vendors:
            inputs:
                - 'bundles/fosjsrouting/js/router.js'
                - 'js/fos_js_routes.js'
                - 'js/vendor/jQuery/jquery-2.1.3.js'
                - 'js/vendor/jQuery/jquery-migrate-1.2.1.js'
                - 'js/vendor/Bootstrap/bootstrap.min.js'
                - 'js/vendor/AngularJS/angular.min.js'
                - 'js/vendor/AngularJS/angular-route.min.js'
                - 'js/vendor/AngularJS/angular-animate.min.js'
                - 'js/vendor/AngularJS/angular-translate.js'
                - 'js/vendor/AngularJS/angular-translate-loader-static-files.js'
                - 'js/vendor/AngularJS/scrollglue.js'
                - 'js/vendor/angular-busy/angular-busy.js'
                - 'js/vendor/angular-notify/angular-notify.js'
                - 'js/vendor/tg-angular-validator/angular-validator.min.js'
                - 'js/vendor/angular-no-captcha/angular-no-captcha.min.js'
                - 'js/fos_js_routes.js'
        modules:
            inputs:
                - 'js/custom/riki34.module.js'
                - 'js/custom/appCore.js'
        services:
            inputs:
                - 'js/custom/Service/*'
        models:
            inputs:
                - 'js/custom/Model/*'
        controllers:
            inputs:
                - 'js/custom/Controller/*'
        directives:
            inputs:
                - 'js/custom/Directive/*'
