imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: framework.yml }
    - { resource: twig.yml }
    - { resource: assetic.yml }
    - { resource: doctrine.yml }
    - { resource: swiftmailer.yml }
    - { resource: knp_paginator.yml }
#    - { resource: hwi_oauth.yml }



