# Doctrine Configuration
doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "localhost"
        port:     "%database_port%"
        dbname:   "naidusvoe"
        user:     "root"
        password: "12345"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true