hwi_oauth:
    firewall_name: secured_area
    resource_owners:
        vkontakte:
            type:          vkontakte
            client_id:     %app_vk_id%
            client_secret: %app_vk_key%
            scope:         "email"

        facebook:
            type:          facebook
            client_id:     %app_fb_id%
            client_secret: %app_fb_key%
            scope:         "email"