security:
    encoders:
        NaidusvoeBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    providers:
        user_db:
            entity: { class: NaidusvoeBundle\Entity\User }
        #hwi:
        #    id: naidusvoe.hwi

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false
            anonymous: ~

        secured_area:
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                always_remember_me: true
            #oauth:
            #    remember_me: true
            #    resource_owners:
            #        facebook: "/login/check-facebook"
            #        vkontakte: "/login/check-vkontakte"
            #    login_path:        /login
            #    failure_path:      /login
            #    oauth_user_provider:
            #        service: naidusvoe.hwi
            pattern:    ^/
            anonymous: ~
            form_login:
                remember_me: true
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /